name: 'dwh_project'
version: '1.0.0'
config-version: 2

profile: 'dwh_project'

model-paths:    ["models"]
analysis-paths: ["analyses"]
seed-paths:     ["seeds"]
test-paths:     ["tests"]
macro-paths:    ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dwh_project:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
